name: Deploy to fly.io
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Check for FLY_API_TOKEN
        run: |
          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
            echo "::error::FLY_API_TOKEN is not set in repository secrets"
            echo "Please add your Fly.io API token as a repository secret named FLY_API_TOKEN"
            exit 1
          fi
      - name: Deploy app on fly.io
        run: flyctl deploy --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Check deployment status
        run: flyctl status
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
